export const ADD_RESULTS = "ADD_RESULTS";
export const SET_RESULTS_ORDER = "SET_RESULTS_ORDER";
export const SET_RESULTS_ASC = "SET_RESULTS_ASC";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_FAVOURITES = "SET_FAVOURITES";
export const SET_FAVOURITES_FILTER = "SET_FAVOURITES_FILTER";